<?php

class CSVTest extends PHPUnit_Framework_TestCase
{
	public function testCharsetEncoding()
    {
		$fp = @fopen ('E:\www\yii\demos\product_import\test-shops.csv', 'r');
		if (!$fp) {
			$this->assertNotEmpty($fp, 'CSV test file not found!');
			return false;
		}

		//CSV generated by MS Excel is saved in CP1250 encoding
		//we convert it to UTF-8 on the fly
		$filter = stream_filter_prepend($fp, 'convert.iconv.CP1250/UTF-8');

		//Function str_getcsv responsible for reading csv data is locale dependent
		setlocale(LC_CTYPE, "pl_PL.utf8");
		
		while ($row = fgets($fp, 2000)) {
			$csvData[] = str_getcsv($row, ';');
		}

		fclose($fp);

       
		
		//I use md5() here as it is an easy way to prove that we got proper encoding 
		//and is proof against any possible errors with encoding in this unit test file itself 
		//(ie. is independent this file encoding)
		
		//For a test, comment out the above line: 
		//$filter = stream_filter_prepend($fp, 'convert.iconv.CP1250/UTF-8');
		$this->assertEquals('f717f01690365c6733b04305e2ad8d7e', md5($csvData[0][0].$csvData[0][1].$csvData[0][2].$csvData[0][3]), 
			'First line of test-shops.csv has probably charset encoding broken.');
     }
}

?>
